# site settings
title: Jason and Bailey
description: October 2022
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jasonandbailey.github.io #https://jasonandbailey.com # the base hostname & protocol for your site
author: Bailey Steinfadt

# homepage tt@github.com:jasonandbailey/forty-jekyll-theme.gitiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
